dataset_builder: &ds_builder
    vocab_path: 'ocr_crnn/configs/vocab.txt'
    img_width: 128
    img_height: 32
    channel: 1

train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        'ocr_crnn/configs/df_train.csv'
    val_csv_path:
        'ocr_crnn/configs/df_val.csv'
    test_csv_path:
        'ocr_crnn/configs/df_test.csv'
    batch_size_per_replica: 64
    # Number of epochs to train.
    epochs: 1
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0
    earlystopping:
        patience: 2
        restore_best_weights: True
    fit_verbose: 1
