dataset_builder: &ds_builder
    vocab_path: 'ocr_crnn/configs/vocab.txt'
    img_width: 200
    img_height: 32
    channel: 1

train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        'ocr_crnn/configs/df_data.csv'

    batch_size_per_replica: 16
    num_kfold: 5
    # Number of epochs to train.
    epochs: 20
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0
    earlystopping:
        patience: 10
    fit_verbose: 1
